### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by evancollins1** [dacase/nabc#2]
Hi,

I saw that NAB is no longer part of AMBER so I wanted to use this GitHub repository. I installed it according to the instructions you provided on the README.

To contextualize my likely simple question, I want to run the these two commands.

```
nab mrna.nab
./a.out
```

This is to ultimately generate a .pdb file for a small RNA sequence.

How do I do this? I see there is a 'nab' folder under 'src' but don't know how to run these commands. It says command 'nab' not found. I also tried cd src/nab and then running ./mrna.nab, but it says... "syntax error near unexpected token '('.

Note, this is my mrna.nab file.

```
molecule m;

m = fd_helix("arna", "auggaggacgccaagaacau", "rna");
putpdb("mrna.pdb", m, "-wwpdb");
```

**Comment by evancollins1** [comment]
Thanks for this. I tried running...

```
cd nabc/bin
./nab mrna.nab
```
It returned this error
```
/home/andersonxps/anaconda3/envs/md-intro-tutorial/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/andersonxps/evan/md/nabc/lib/libsff.a(sff.o): in function `egb_hcp_rbondi':
/home/andersonxps/evan/md/nabc/src/sff/hcp_gb.c:98: undefined reference to `_ZGVbN2v_cbrt'
/home/andersonxps/anaconda3/envs/md-intro-tutorial/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/andersonxps/evan/md/nabc/src/sff/hcp_gb.c:108: undefined reference to `_ZGVbN2v_cbrt'
/home/andersonxps/anaconda3/envs/md-intro-tutorial/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/andersonxps/evan/md/nabc/src/sff/hcp_gb.c:116: undefined reference to `_ZGVbN2v_cbrt'
/home/andersonxps/anaconda3/envs/md-intro-tutorial/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/andersonxps/evan/md/nabc/src/sff/hcp_gb.c:98: undefined reference to `_ZGVbN2v_cbrt'
/home/andersonxps/anaconda3/envs/md-intro-tutorial/bin/../lib/gcc/x86_64-conda-linux-gnu/12.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/andersonxps/evan/md/nabc/src/sff/hcp_gb.c:108: undefined reference to `_ZGVbN2v_cbrt'
collect2: error: ld returned 1 exit status
cc failed!
```

Despite this error, it seems like a file .mrna.c was produced in the bin folder. Note that mrna.nab is also in 

How can I obtain the .pdb file? Thanks -  I am new to NAB.

**Comment by evancollins1** [comment]
Question: I was hoping for a single-stranded .pdb for my RNA sequence. I noticed the outputted .pdb was a double-stranded helix. How can I obtain just the single-stranded .pdb?
________

Thanks. Exiting the conda environment solved it. 

For anyone reading this in the future, here is a comprehensive solution for installation and running a basic `nab` command as of January 2024.

- Download AmberTools23 via conda as described here: https://ambermd.org/GetAmber.php. Make sure to `conda deactivate` prior to working with NABC.
- Download NABC (and NAB) as instructed on this GitHub repo
- In terminal, 
```
export AMBERHOME=/anaconda3/envs/AmberTools {or whereever your conda envs are stored}
export PATH=$PATH:$AMBERHOME/bin
cd nabc/bin {or wherever your nabc/bin folder is located; make sure .nab file you created is stored here too}
./nab mrna.nab {or whatever you command you want to run}
./a.out
```

The `bin` folder should now contain the .pdb file.

**Comment by james-vincent** [comment]
Is a gcc compiler required at run time? We had the same situation with a conda install of nabc. Running nab looks for the compiler. We cannot distribute a compiler with nab. Can it be installed, and will it run, in a self contained way?

**Comment by james-vincent** [comment]
When we run nab, on various machines, it seems to be looking for the gcc that it was built with, not the gcc available in the path. For example on macs we use spack to install. The nab executable seems to be looking for the spack compiler (which is no longer in place). It does not find the gcc that is already in PATH:
```

% nab ./dna.nab 
[spack cc] ERROR: Spack compiler must be run from Spack! Input 'SPACK_ENV_PATH' is missing.
C compiler failed with exit code 256
sbtest@sbgrid-m11 /tmp % which gcc
/usr/bin/gcc
sbtest@sbgrid-m11 /tmp % gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
```
