### ISSUE TITLE
Installation problem for PATH

### ISSUE THREAD

**Issue by WenSheng-Ye** [dacase/nabc#6]
Thank you, first of all, for the excellent software.

But I have faced a problem with installation. I have used the source codes for installation on Ubuntu 20.04.06, after this line for configure-"./configure", the system can pass the test for nab. 
Unfortunately, I could not use nabc with my file to create a nuclear acid sequence. After the line-"which nabc", it returned nothing.
And after the line-"find . -name nabc", it returned a path in the source file folder that I made in my folder.
I think I may did something wrong, hope can ger your help.

**Comment by dacase** [comment]
I know this is really old, and I'm not sure why the answer has never appeared here.  (Maybe I replied via email??)

Anyway, `nabc` is not an executable; rather `libnabc` is a library that you would link into "C" programs that you would write.  Look in the `test/nabc` folder for examples of such driver programs.
